Repository voxpupuli/voxpupuli-puppet-lint-plugins, pull requests merged in 2021-11, with the labels that each got.

#7 Add puppet-lint-lookup_in_parameter-check
  voxpupuli-puppet-lint-plugins.gemspec
Labels: backwards-incompatible

#9 Implement Rubocop linting
  .github/workflows/test.yml
  .rubocop.yml
  Gemfile
  Rakefile
  voxpupuli-puppet-lint-plugins.gemspec
Labels: enhancement

#13 Drop puppet-lint-params_empty_string-check
  voxpupuli-puppet-lint-plugins.gemspec
Labels: skip-changelog

#12 Add puppet-lint-param-types
  voxpupuli-puppet-lint-plugins.gemspec
Labels: backwards-incompatible

#10 Add puppet-lint-param-docs
  voxpupuli-puppet-lint-plugins.gemspec
Labels: backwards-incompatible

#14 Add rubocop-rake
  .rubocop.yml
  voxpupuli-puppet-lint-plugins.gemspec
Labels: skip-changelog

#8 Add puppet-lint-params_empty_string-check
  voxpupuli-puppet-lint-plugins.gemspec
Labels: backwards-incompatible

#15 Release 3.0.0
  CHANGELOG.md
  voxpupuli-puppet-lint-plugins.gemspec
Labels: skip-changelog
